### PR TITLE
fix: upgrade dart

### PR DESCRIPTION
**Pull request by SputNikPlop**

### CODE REVIEW

**Comment by Kounex** [comment]
Thanks for hanging in and contributing! Currently I don't have the time I would like to have to work on this but this will change again! Will soon take a fresh view on the app and look to your dependency updates as well 😊

**Comment by SputNikPlop** [comment]
> Thanks for hanging in and contributing! Currently I don't have the time I would like to have to work on this but this will change again! Will soon take a fresh view on the app and look to your dependency updates as well 😊

There is some stuff now with flutter 3.10 that I haven't managed to check out and fix as well so this is still kinda a WIP

**Comment by SputNikPlop** [comment]
@Kounex This is ready to be reviewed, merged with most of your upgrades while resolving some minor issues.

**Comment by Kounex** [comment]
Perfect, thanks a lot! :)

**Pull request merged**
